import "./globals.css";
import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.css";
import Footer from "sponsorbook/components/footer";
import Navbar from "sponsorbook/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "SponsorBook",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <div className="container">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
